<?xml version="1.0" ?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://staxer.sample/"
                  name="staxerSampleService" targetNamespace="http://staxer.sample/">
    <wsdl:import namespace="http://staxer.sample/" location="staxerSampleBase.wsdl"/>
    <wsdl:binding name="staxerSampleService" type="tns:staxerSampleService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

        <wsdl:operation name="echoXsdTypes">
            <soap:operation soapAction="echoXsdTypes" style="document"/>
            <wsdl:input name="echoXsdTypes">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="echoXsdTypesResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="echoCustomTypes">
            <soap:operation soapAction="echoCustomTypes" style="document"/>
            <wsdl:input name="echoCustomTypes">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="echoCustomTypesResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

    </wsdl:binding>

    <wsdl:service name="staxerSampleService">
        <wsdl:port binding="tns:staxerSampleService" name="staxerSampleService">
            <soap:address location="http://localhost:8080/webapp/servlet"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
